### ISSUE TITLE
Maven project

### ISSUE THREAD

**Issue by denisw** [buddycloud/buddycloud-server-java#1]
It seems that currently, the only "build system" used for the server is an Eclipse project. I think this should be structured as a Maven project so that we get all the goodies like IDE independence, automatic dependendy downloads etc.

**Comment by anbumca** [comment]
Hi 

How to install buddycloud server using windows system.

Thanks and Regards,
Anbarasan S

**Comment by lloydwatkin** [comment]
Hi @anbumca afraid I can't help you, you'll need to determine how to run a maven/java project on windows, maybe this would help https://maven.apache.org/guides/getting-started/windows-prerequisites.html
