### ISSUE TITLE
docu typo: disover -> discover

### ISSUE THREAD

**Issue by robotnic** [buddycloud/buddycloud-server-java#297]
There is a typo:
https://xmpp-ftw.jit.su/manual/extensions/buddycloud/#discovering-media-servers

```
socket.send(
    'xmpp.buddycloud.disover.media-server',
    {
        "of": "evilprofessor.co.uk"
    },
    function(error, data) { console.log(error, data) }
)
```

**Comment by lloydwatkin** [comment]
Hi, @robotnic can you raise this against the xmpp-ftw-demo (documentation) repo then https://github.com/xmpp-ftw/xmpp-ftw-demo as its unrelated to the server. (Even better you can use github UI to fork, edit, and make a pull request with a fix easily :+1: ).
