### ISSUE TITLE
media server mime type for json

### ISSUE THREAD

**Issue by robotnic** [buddycloud/buddycloud-server-java#314]
I tried to post json data to the media server.
The mimetype got lost
https://buddycloud.org/api/robotnic@buddycloud.org/media/eE5XICaZ3yj1eKkfYkb7/metadata

The mimetype for json is:
"application/json"

Background: I want to store map data in geojson format at the mediaserver.

**Comment by lloydwatkin** [comment]
This isn't a channel server issue but a media server problem. I think it if doesn't understand the MIME type it will store as generic. Although it does seem like there is some support for it https://github.com/buddycloud/buddycloud-media-server/blob/c13c34b5f75af4f7ddff8b07abe58621ed80c5d2/src/main/java/com/buddycloud/mediaserver/business/util/MimeTypeMapping.java#L26

Does your source file have a mime type? What is the media server reporting back with?

Also: I'm closing this, please can you raise an issue against the media server and reference this issue?
