### ISSUE TITLE
Unable to download Buddycloud Server

### ISSUE THREAD

**Issue by Pkaran01** [buddycloud/buddycloud-server-java#318]
hello i follows your instruction on http://buddycloud.com/install

i done all the step but i am unable to get your web server. through this link. i am using Ubuntu 16.04.1 x64

http://downloads.buddycloud.com/packages/debian/nightly/buddycloud-server-java/

**Comment by lloydwatkin** [comment]
I believe buddycloud/buddycloud.com#98 and this are duplicates/same issue so I'm closing this in favour of the other issue. Hopefully your problem will be sorted soon.
